version: '2'
services:
  sut:
    extends:
      file: docker-compose.common.yml
      service: web
    build: .
    image: appcelerator/amp-demo-service:test
    environment:
      DEBUG: app*
      NODE_ENV: development
    command: npm test
